name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Build and test with bin/rails test
      run: |
        gem install bundler:1.15.2 
        bundle install --jobs 4 --retry 3
        bin/rails test
